# Generated by Django 3.2.12 on 2022-02-19 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wotwatcher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tankexpectations',
            name='tank_name',
            field=models.CharField(max_length=150, null=True, unique=True),
        ),
    ]
