# Generated by Django 3.2.12 on 2022-02-19 13:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wotwatcher', '0002_tankexpectations_tank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TankRatingSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wot_username', models.CharField(max_length=150)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wotwatcher.tankexpectations')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
